### ISSUE TITLE
[Flutter Web] Text not appearing in country picker

### ISSUE THREAD

**Issue by lmordell** [imtoori/CountryCodePicker#127]
On Flutter web, when I open the country picker, the text and search bar are blank:

![image](https://user-images.githubusercontent.com/14003742/100005896-837bf400-2d7e-11eb-87ca-0b350aafb74b.png)

Here's my `TextFormField` definition:

```
TextFormField(
    controller: _phoneController,
    keyboardType: TextInputType.phone,
    decoration: InputDecoration(
        hintText: 'Enter your phone number',
        labelText: 'Phone',
        prefixIcon: CountryCodePicker(
        onChanged: (CountryCode code) {
            _countryCode = code.dialCode;
        },
        initialSelection: '+1',
        favorite: ['+1', 'US'],
    ),
)
```

**Comment by bbarwik** [comment]
Try to add
```
dialogBackgroundColor: Theme.of(context).backgroundColor,
```
or 
```
textStyle: TextStyle(
                      color: Colors.black
                    )
```
It solved this issue for me, however, in the end I decided to use another package.

**Comment by imtoori** [comment]
solved in latest release

**Comment by golane-august** [comment]
Still not fixed: it uses white as fallback color. Not the `Theme.of(context).cardColor`:
https://github.com/imtoori/CountryCodePicker/blob/a4b2fe3179ca0474569f69a0c05d57fc5bd8a9f1/lib/selection_dialog.dart#L71
